//PREGUNTAS TECNICAS DE PROGRAMACION Y MAQUETADO

/*12 DE JULIO DE 2022=> ENTENDER Y EXPLICAR LOS SIGUIENTES CONCEPTOS:

A)QUE ES ASINCRONIA
B)QUE ES UNA CALLBACK
C)QUE ES HOISTING
D)QUE ES EL SCOPE
E)VAR, LET, CONST
F)FUNCION DECLARADA,FUNCION EXPRESADA,FUNCION ANONIMA
G)ARROW FUNCTIONS
*/
