//PREGUNTAS TECNICAS DE PROGRAMACION Y MAQUETADO

/*12 DE JULIO DE 2022=> ENTENDER Y EXPLICAR LOS SIGUIENTES CONCEPTOS:

A)QUE ES ASINCRONIA
B)QUE ES UNA CALLBACK
C)QUE ES HOISTING
D)QUE ES EL SCOPE
E)VAR, LET, CONST
F)FUNCION DECLARADA,FUNCION EXPRESADA,FUNCION ANONIMA
G)ARROW FUNCTIONS
H)QUE ES EL AMBITO DE UNA FUNCION
EL AMBITO HACE REFERENCIA A DONDE ESTAN DISPONIBLES ESTAS VARIABLES PARA SU USO.TENEMOS UN AMBITO LOCAL/DE FUNCION , UN AMBITO GLOBAL Y AMBITO DE BLOQUE.

EL HOISTING ES UN MECANISMO DE JAVASCRIPT EN EL CUAL LAS VARIABLES Y LA DECLARACION DE FUNCIONES SE MUEVEN A LA PARTE SUPERIOR DE SU AMBITO ANTES DE LA EJECUCION DEL CODIGO.


*/

//EL PROBLEMA QUE PRESENTA EL VAR SON LAS REASIGNACIONES QUE SI SE HACEN A PROPOSITO ESTA BIEN PERO DE LO CONTRARIO LLEVARIA A PROBLEMAS DE CODIGO

// var saludo = 'hola';

// var number = 3;
// if (number > 2) {
//   var saludo = 'dice hola tambien';
// }

// console.log(saludo);

//ENTENDIENDO LET
// OBVIAMENTE LET VIENE A SER LA SOLUCION AL PROBLEMA QUE TRAIAMOS CON VAR.
// QUE ES UN BLOQUE: UN BLOQUE ES UN PEDAZO DE CODIGO QUE VIVE ENTRE LLAVES{}.AHORA RECORDAR QUE AMBITO DE BLOQUE NO ES LO MISMO QUE AMBITO LOCAL/DE FUNCION YA QUE AMBITO LOCAL SE REFIERE A AMBITO ENMARCADO DENTRO DE UNA FUNCION Y EL AMBITO DE BLOQUE SE REFIERE A EL PEDAZO DE CODIGO DELIMITADO POR LLAVES Y ESTE PUEDE SER MAS ROBUSTO CONTENIENDO VARIAS FUNCIONES INCLUSO FUNCIONES ANIDADAS DENTO DEL MISMO.

// AHORA SI TE PUEDO EXPLICAR QUE LET ES UNA MANERA DE DECLARAR VARIABLES Y SU PARTICULARIDAD ES QUE TIENE AMBITO DE BLOQUE.LAS VARIABLES LET TIENEN UN ALCANCE DE BLOQUE.
let numero = 3;

if (numero > 3) {
  let hola = 'esta saludando';
  console.log(hola);
}

PLANTEANDO LA DIFERENCIA ENTRE LET Y VAR
PRIMERO EXPLICAR QUE ES DECLARAR UNA FUNCION Y QUE ES ACTUALIZAR UNA FUNCION.
UNA VARIABLE SE DECLARA CUANDO SE PLANTEA CON SU IDENTIFICADOR SIN ASIGNARLE VALORES.|
var arbol;
let reloj;
let numero;   ...etc
AHORA A ESA VARIABLE SE LE PUEDE ASIGNAR UN VALOR MEDIANTE EL OPERADOR DE ASIGNACION
var arbol = 'soy un arbol';
let reloj='es un reloj';
let numero=3;
SABIENDO LO ANTERIOR TAMBIEN ES CIERTO QUE UNA VARIABLE SE PUEDE ACTUALIZAR, OJO LO CUAL ES DIFERENTE A REDECLARAR.ACTUALIZAR SOLO IMPLICA REASIGNARLE VALOR PERO REDECLARAR IMPLICA EL USO DE LA PALABRA RESERVADA DE LA VARIABLE.(PALABRAS RESERVADAS SON VAR,LET,CONST IDENTIFICADORES SON LOS NOMBRES DE LA FUNCION O SEQUENCIA DE CARACTERES UNICODE)
UNA VARIABLE SE ACTUALIZA CUANDO SIN HACER USO DEL IDENTIFICADOR DE LA VARIABLE SE LE REASIGNA UN VALOR.EJ

var arbol = 'soy un arbol';
arbol= ahora soy otro arbol;

let reloj='es un reloj';
reloj='ahora es otro reloj';

let numero =3;
numero=8;

SABIENDO LO ANTERIOR YA SE PUEDE EXPLICAR QUE LET PERMITE ACTUALIZAR VARIABLES DENTRO DE SU AMBITO DE BLOQUE PERO NO SE PUEDE REASIGNAR A DIFERENCIA DE VAR QUE PUEDE SER ACTUALIZADA Y ADEMAS REDECLARADA;

LO SIGUIENTE ES ACTUALIZAR: let saludar = "dice Hola";
                            saludar = "dice Hola tambien";//PILLA QUE NO USAMOS EL IDENTIFICADOR LET
LO SIGUIENTE ES REDECLARAR
let saludar = "dice Hola";
    let saludar = "dice Hola tambien"; // error: Identifier 'saludar' has already been declared  //MIRA EL ERROR QUE BOTA PORQUE HEMOS USADO EL IDENTIFICADOR DOS VECES


AHORA SI LA MISMA VARIABLE SE DECLARA EN AMBITOS DISTINTOS CON VALORES DISTINTOS NO PASA NADA PORQUE SON TRATADAS COMO VARIABLES INDEPENDIENTES YA QUE TIENEN AMBITOS DIFERENTES.   
AHORA COMO UNA VARIABLE CON LA PALABRA RESERVADA LET NO PUEDE SER DECLARADA DOS VECES DENTRO DE UN AMBITO EL PROBLEMA CON VAR YA DESAPARECERIA
AL IGUAL QUE CON AQUELLAS VARIABLES DECLARADAS CON LA PALABRA RESERVADA VAR , LAS VARIABLES QUE SE DESIGNAN CON LET TAMBIEN PRESENTAN HOISTING SOLO QUE SI INTENTAS INICIALIZARLA ANTES DE DECLARARLA TE BOTA UN REFERENCE ERROR, A DIFERENCIA QUE CON VAR QUE TE BOTA UN UNDEFINED